### ISSUE TITLE
Cannot be generated properly

### ISSUE THREAD

**Issue by NativeStudio2021** [Synthlight/RE-Editor#6]
missing Enums_Internal.hpp can't be generated properly, I don't know where I can download this file, is it possible to provide Enums_Internal.hpp file?

**Comment by Synthlight** [comment]
Open the object explorer in-game and REF creates it for you.
You don't need to dump the SDK, literally just opening the OE will create the file.

**Comment by NativeStudio2021** [comment]
Thank you very much, I'll try ^_^

**Comment by Synthlight** [comment]
I'm assuming you got it done. I also updated the readme to note how to get the required dependencies.
Either way, closing this as solved.
