### ISSUE TITLE
Could you add a way to change entire selected rows/columns?

### ISSUE THREAD

**Issue by NIGELTEAPOT** [Synthlight/RE-Editor#7]
In excel, you can make a selection and then press ctrl+enter to change all of the cells selected to the new value.

Since the program looks like excel, and involves changing a lot of values at once, this would be VERY helpful.

**Comment by Synthlight** [comment]
This isn't excel.
You aren't the first to ask, and I doubt you'll be the last to, but I have no intention of doing this.

**Comment by NIGELTEAPOT** [comment]
Yes, excel is useful.  This could be too.
